# Importing Libraries and Data Processing

In [2]:
import pandas as pd
import numpy as np
#df = pd.read_csv("att-start-1.csv")
#print(df)

In [4]:
with open("att-start-1.csv") as f:
    # use the first line as column names in the dataframe
    col_names = f.readline()
    df = pd.DataFrame(columns = col_names.split(","), dtype=object)
    #print(col_names)
    for line in f:
        d = {}
        # lines have more than 2 columns, but the trailing values are empty
        # so the format is col1, large_col2,...
        col1, *col2 = line.split(",")
        d["sku"] = col1
        for item in col2:
            try:
                if item.strip(): #disregard the empty trailing columns
                    k,v = item.split("=")
                    # we split on comma, so have occasional
                    k = k.strip('"')
                    v = v.strip('"')
                    d[k] = v
            except ValueError as e:
                # there is a column value with missing key
                print("Could not assign to column:", d["sku"], item)
                
        for col in df.columns:   # add potentially missing columns as None
            if col not in d:
                d[col] = None
        df = df.append(d, ignore_index = True)

print(df)

Could not assign to column: PRACLA16  16 months on less
              sku alchool                                          alt_image  \
0         ILFOLLO    None                                               None
1    SMANGRUJ05-1      10            /a/n/anghelo_rujo_edited-pixlr_copy.jpg
2      OLBCANGR15      10                            /c/a/cangrande_test.jpg
3        ZAMFIA19      10  /p/i/pierluigi_zampaglione_fiano_don_chisciott...
4        VINMUL18      10     /r/u/rudi_vindimian_muller_turgau_vinmul18.png
..            ...     ...                                                ...
379       MAZCH20    None        /t/e/tenuta_mazzolino_blanc_mazch19_1_1.png
380      PEDNOS20    None                                               None
381      LEDSRO18    None  /l/e/le_due_terre_sacrisassi_rosso_ledsro17_1.jpg
382     FSLOCHE20    None                                               None
383       PGMOS21    None           /p/i/piero_gatti_moscato_pgmos19_1_1.png

    animal                        area australian_like awards blended_grapes  \
0        1                        None            None   None           None
1        2                     Alghero            None   None           None
2     None                     Gallura            None   None       Cannonau
3     None                     Irpinia            None   None           None
4     None                 Vallagarina            None   None           None
..     ...                         ...             ...    ...            ...
379   None              Oltrepo Pavese            None   None           None
380   None             Valle dei Laghi            None   None           None
381   None  Colli Orientali del Friuli            None   None        Refosco
382   None            Castelli di Jesi            None   None           None
383   None                       Cuneo            None   None           None

    bottleml box_size  ... vegetal vineyard_management  Vntg wild_ferment  \
0        750       12  ...       1         Sustainable  None         None
1       None        1  ...       1                None  2005         None
2        750        6  ...    None             Organic  2015         None
3        750        6  ...    None             Organic  2019         None
4        750       12  ...    None             Organic  2018         None
..       ...      ...  ...     ...                 ...   ...          ...
379      750       12  ...    None         Sustainable  2020         None
380      750       12  ...    None             Organic  2020         None
381      750        6  ...    None             Organic  2018         None
382      700       12  ...    None          Biodynamic  2020         None
383      750        6  ...    None         Sustainable  2021         None

    wine_producer\n mayob_btb          wine_producer style organic  myob
0              None     43340               Il Follo   NaN     NaN   NaN
1              None     43340          Sella & Mosca   NaN     NaN   NaN
2              None     43340          Tenute Olbios   NaN     NaN   NaN
3              None     43340  Pierluigi Zampaglione   NaN     NaN   NaN
4              None     43340         Rudi Vindimian   NaN     NaN   NaN
..              ...       ...                    ...   ...     ...   ...
379            None     43340       Tenuta Mazzolino  None    None  None
380            None     43340          Gino Pedrotti  None    None  None
381            None     43340           Le Due Terre  None    None  None
382            None     43340   Fattoria San Lorenzo  None    None  None
383            None     43340            Piero Gatti  None    None  None

[384 rows x 52 columns]

In [5]:
df.iloc[0:5,:]      # when calling the column and row you want with using number

,sku,alchool,alt_image,animal,area,australian_like,awards,blended_grapes,bottleml,box_size,...,vegetal,vineyard_management,Vntg,wild_ferment,wine_producer\n,mayob_btb,wine_producer,style,organic,myob
0,ILFOLLO,None,None,1,None,None,None,None,750,12,...,1,Sustainable,None,None,None,43340,Il Follo,NaN,NaN,NaN
1,SMANGRUJ05-1,10,/a/n/anghelo_rujo_edited-pixlr_copy.jpg,2,Alghero,None,None,None,None,1,...,1,None,2005,None,None,43340,Sella & Mosca,NaN,NaN,NaN
2,OLBCANGR15,10,/c/a/cangrande_test.jpg,None,Gallura,None,None,Cannonau,750,6,...,None,Organic,2015,None,None,43340,Tenute Olbios,NaN,NaN,NaN
3,ZAMFIA19,10,/p/i/pierluigi_zampaglione_fiano_don_chisciott...,None,Irpinia,None,None,None,750,6,...,None,Organic,2019,None,None,43340,Pierluigi Zampaglione,NaN,NaN,NaN
4,VINMUL18,10,/r/u/rudi_vindimian_muller_turgau_vinmul18.png,None,Vallagarina,None,None,None,750,12,...,None,Organic,2018,None,None,43340,Rudi Vindimian,NaN,NaN,NaN

In [11]:
df.iloc[0][["alchool"]]     # when calling the column and row you want with using columns name such as "alchool"

alchool    None
Name: 0, dtype: object

In [8]:
df.iloc[0][["alchool"]] = 0     # assigning or changing a variable
df.iloc[0:5,:]

,sku,alchool,alt_image,animal,area,australian_like,awards,blended_grapes,bottleml,box_size,...,vegetal,vineyard_management,Vntg,wild_ferment,wine_producer\n,mayob_btb,wine_producer,style,organic,myob
0,ILFOLLO,0,None,1,None,None,None,None,750,12,...,1,Sustainable,None,None,None,43340,Il Follo,NaN,NaN,NaN
1,SMANGRUJ05-1,10,/a/n/anghelo_rujo_edited-pixlr_copy.jpg,2,Alghero,None,None,None,None,1,...,1,None,2005,None,None,43340,Sella & Mosca,NaN,NaN,NaN
2,OLBCANGR15,10,/c/a/cangrande_test.jpg,None,Gallura,None,None,Cannonau,750,6,...,None,Organic,2015,None,None,43340,Tenute Olbios,NaN,NaN,NaN
3,ZAMFIA19,10,/p/i/pierluigi_zampaglione_fiano_don_chisciott...,None,Irpinia,None,None,None,750,6,...,None,Organic,2019,None,None,43340,Pierluigi Zampaglione,NaN,NaN,NaN
4,VINMUL18,10,/r/u/rudi_vindimian_muller_turgau_vinmul18.png,None,Vallagarina,None,None,None,750,12,...,None,Organic,2018,None,None,43340,Rudi Vindimian,NaN,NaN,NaN

In [9]:
df.iloc[0][["alchool"]] = None      # undo the changes
df.iloc[0:5,:]

,sku,alchool,alt_image,animal,area,australian_like,awards,blended_grapes,bottleml,box_size,...,vegetal,vineyard_management,Vntg,wild_ferment,wine_producer\n,mayob_btb,wine_producer,style,organic,myob
0,ILFOLLO,None,None,1,None,None,None,None,750,12,...,1,Sustainable,None,None,None,43340,Il Follo,NaN,NaN,NaN
1,SMANGRUJ05-1,10,/a/n/anghelo_rujo_edited-pixlr_copy.jpg,2,Alghero,None,None,None,None,1,...,1,None,2005,None,None,43340,Sella & Mosca,NaN,NaN,NaN
2,OLBCANGR15,10,/c/a/cangrande_test.jpg,None,Gallura,None,None,Cannonau,750,6,...,None,Organic,2015,None,None,43340,Tenute Olbios,NaN,NaN,NaN
3,ZAMFIA19,10,/p/i/pierluigi_zampaglione_fiano_don_chisciott...,None,Irpinia,None,None,None,750,6,...,None,Organic,2019,None,None,43340,Pierluigi Zampaglione,NaN,NaN,NaN
4,VINMUL18,10,/r/u/rudi_vindimian_muller_turgau_vinmul18.png,None,Vallagarina,None,None,None,750,12,...,None,Organic,2018,None,None,43340,Rudi Vindimian,NaN,NaN,NaN

Operations with missing values

In [10]:
df.isnull().sum()       # how many missing values in which column

sku                            0
alchool                      361
alt_image                    199
animal                       375
area                         150
australian_like              384
awards                       384
blended_grapes               317
bottleml                      11
box_size                       0
cellar_practice               39
country_of_manufacture       384
cost                         375
custom_block                 384
custom_label                 384
filtration                    20
florealnew                   375
fruit                         20
international_awards         384
is_featured                  384
kind                         384
kind_byo_organic              18
main_grape                    31
manufacturer                   6
method                       384
mineral                       20
myob_btb                     384
myob_btc_h                     8
oak1                          20
pairing                       18
price                        384
product_name                 384
region                         4
second_fermentation          328
sparkling_residual_sugar     379
spontaneous_fermentation1     20
skin_contact                  20
sku_short                      0
spice                        375
stripe_sub_enabled             2
sw_featured                   11
tastingnotes                 381
vegetal                      375
vineyard_management           34
Vntg                          34
wild_ferment                 384
wine_producer\n              384
mayob_btb                      8
wine_producer                 20
style                        383
organic                      363
myob                         383
dtype: int64

add  **"inplace=True"**  to make it permanent

df.fillna(value=1, inplace=True)        # all missing value is 1 and permanently changed
df.iloc[0:5,:]

df["alt_image"].fillna(5,inplace=True)        # missing values in selected columns changed permanently
df.iloc[0:5,:]

df.dropna(inplace=True)         # permanently deletes that row if any row has a NaN value

df.dropna(how="any", inplce=True)      # If any row has a NaN value, it means permanently delete that row

df.dropna(how="all",inplace=True)      # if the entire row is in NaN value, it will delete it permanently.

df.dropna(subset=["alchool"],inplace=True)     # permanently deletes only rows with NaN values in column "alchool"

df.dropna(thresh=2)     # If there are at least 2 NaN values in the row, it should not delete that row, but delete the others

df.to_csv("data_parsed.csv") # save edited data